src/com/walmartlabs/lacinia/parser.clj
test/com/walmartlabs/lacinia_test.clj

If inline fragment contains type condition, we should check if this type is defined in schema. At the moment we're throwing NPE. This PR fixes https://github.com/walmartlabs/lacinia/issues/2.
Ping @hlship @bcarrell

Throw exception for inline fragments with invalid type conditions.

---

src/com/walmartlabs/lacinia/internal_utils.clj
src/com/walmartlabs/lacinia/schema.clj

This allow Sets to be used as field values in resolver returned data. Before this patch it errors on a sequential? check and thus disallows the use of Set. This is similar to how json encoders operate (encoding Sets as Arrays).
related to #21

fix condition checking only sequential for collection like things 

---

CHANGES.md
README.md
dev-resources/star-wars-schema.edn
docs/_examples/enum-definition.edn
docs/_examples/overview-exec-query.edn
docs/enums.rst
project.clj
src/com/walmartlabs/lacinia/internal_utils.clj
src/com/walmartlabs/lacinia/introspection.clj
src/com/walmartlabs/lacinia/parser.clj
src/com/walmartlabs/lacinia/schema.clj
test/com/walmartlabs/introspection_test.clj
test/com/walmartlabs/lacinia/enums_test.clj
test/com/walmartlabs/lacinia_test.clj
test/com/walmartlabs/test_schema.clj

This builds on https://github.com/walmartlabs/lacinia/pull/31 (which should be merged first) to convert the internal representation of enums to keywords, which is a more natural fit for Clojure.
This affects existing applications: they can expect to see keywords in field arguments that are of an enum type.  That's alpha for you.

Change internal representation of enum values from string to keyword

---

src/com/walmartlabs/lacinia/parser.clj
src/com/walmartlabs/lacinia/schema.clj
test/com/walmartlabs/lacinia/custom_scalars_test.clj
test/com/walmartlabs/lacinia_test.clj

This PR fixes https://github.com/walmartlabs/lacinia/issues/34
Variables can be custom scalars, and so we should treat them as such when their value is resolved.

Apply custom scalar's parse fn to resolved variables 

---

dev-resources/perf.clj
project.clj

I've simplified the code inside perf.clj to just collect and store the benchmarks; this gets rid of Incanter as a dev dependency.
I'll follow up with R scripts to generate the desired graphs from the CSV file, once I have that figured out.

Simplify benchmark reporting

---

src/com/walmartlabs/lacinia/executor.clj
src/com/walmartlabs/lacinia/parser.clj
test/com/walmartlabs/lacinia/custom_scalars_test.clj

This PR will prevent returning conformed scalar arguments when resolvers return an error.

Error maps may include parsed arguments, causing failures if those parsed values are not JSON serializable

---

CHANGES.md
README.md
docs/_examples/custom-scalars.edn
docs/custom-scalars.rst
src/com/walmartlabs/lacinia/schema.clj

I've noticed that every app we write has cut-and-pasted this, so it must be generally useful.
@sashton @bcarrell

Make schema/as-conformer public

---

CHANGES.md
src/com/walmartlabs/lacinia.clj
src/com/walmartlabs/lacinia/executor.clj
src/com/walmartlabs/lacinia/resolve.clj

Adds a new function, `execute-parsed-query-async` that returns a ResolverResult.  This is a good bridge for pedestal-lacinia to use in order to provide an async handler for executing queries.

Add function c.w.l/execute-parsed-query-async

---

CHANGES.md
dev-resources/timing-schema.edn
docs/_examples/timings.edn
docs/resolve/index.rst
docs/resolve/timing.rst
src/com/walmartlabs/lacinia/executor.clj
src/com/walmartlabs/lacinia/schema.clj
src/com/walmartlabs/lacinia/timings_test.clj

This builds on my prior PR, #49, which should be merged first.
This tracks time to resolve values in non-default resolver functions, and exposes it in the :extensions key of the response map.
I'm pretty happy with how this came out; I think that structuring the data in terms of the query tree, rather than the schema, is the right way to go.
*Update:* I'm starting to think that the query tree is not the right way to go, as it effectively prevents you from aggregating timing data between different queries; if the timings were organized instead by object and field, it would be simple to aggregate. Thoughts?

Collect timing information from resolvers (optionally)

---

dev-resources/unknown-argument-type-schema.edn
src/com/walmartlabs/lacinia/schema.clj
test/com/walmartlabs/lacinia/arguments_test.clj

When the argument to a field is of an unknown type, a schema compilation exception is thrown.
However, creating the message for that exception throws a new exception, in certain circumstances.
This was due to the type system changes; I've checked for other incorrect uses of the :type keyword,
and the rest look to be legit.

Double exception reporting unknown field argument type

---

CHANGES.md
src/com/walmartlabs/lacinia/parser.clj
test/com/walmartlabs/lacinia/parser_test.clj

Fixed #64
This is a quicky; it extracts the root fields and type of query (query or mutation) from the parsed query.
Perhaps in the future, there will be subscriptions as well, so it isn't just a boolean for mutation?.

Add an API for identifying operations in the query

---

CHANGES.md
dev-resources/com/walmartlabs/test_utils.clj
dev-resources/selections-schema.edn
dev-resources/user.clj
docs/_examples/selections-tree.edn
docs/_examples/selects-field.edn
docs/resolve/index.rst
docs/resolve/overview.rst
docs/resolve/selections.rst
src/com/walmartlabs/lacinia/constants.clj
src/com/walmartlabs/lacinia/executor.clj
src/com/walmartlabs/lacinia/schema.clj
test/com/walmartlabs/lacinia/selections_tests.clj
test/com/walmartlabs/lacinia_test.clj

Fixes #65 
We've been doing this in our apps by pulling apart the selections context key, even though its structure is explicitly private and subject to change. This provides the missing API needed to determine whether a field is present.

Allow field resolvers to identify nested fields in the selection tree

---

CHANGES.md
project.clj
src/com/walmartlabs/lacinia/schema.clj

Mark private-ish functions as :no-doc
Allow the schema/compile options to be nil
Fixes #71

Cleanup from 0.17.0

---

README.md
docs/index.rst

A few updates
- Cleaned up and simplified the text, improved the marketing 
- Fixed the examples because the default is not to do the underscore-to-dash translation
- pedestal-lacinia is now named lacinia-pedestal

Simplify docs, update for rename of lacinia-pedestal

---

CHANGES.md
dev-resources/fixes-types-schema.edn
docs/resolve/index.rst
docs/resolve/overview.rst
docs/resolve/type-tags.rst
src/com/walmartlabs/lacinia/schema.clj
test/com/walmartlabs/lacinia/fixed_types_test.clj

This restores the simpler behavior from 0.16.0 (it uses metadata nearly all the time), but still supports Java objects as resolved values (which apparently is really needed when using Datomic's API).
Fixes #74

Use metadata again, when possible, for type tagging

---

src/com/walmartlabs/lacinia/executor.clj
test/com/walmartlabs/lacinia/selections_tests.clj

Queries that include introspective fields like `__typeName` are currently throwing NullPointerExceptions when using the selections API because they don't have `type-name` or `field-name`.
It's difficult to establish what the type-name or field-name should be for these meta style fields (moreso the type-name), so let's just guard against nils in the selections API for now.

Fix NullPointerException in Selections API

---

.circleci/config.yml
circle.yml

This config enables the use of CircleCI 2.0, which grants an increase in reliability and a decrease in build time from 2 minutes+ to about 12 seconds.

Add CircleCI 2.0 config

---

src/com/walmartlabs/lacinia/schema.clj

This PR addresses a few issues to the use of spec
- Moves the specs into the com.walmartlabs.lacinia.schema namespace
- Explicitly requires the use of simple keywords for keys in the input schema
- Defines :queries and :mutations
- Removes an outdated definition of the :resolve key on a field
- Properly defines the ::type spec (which is recursive!)
Fixes #81

Cleanups for specs in com.walmartlabs.lacinia.schema

---

CHANGES.md
dev-resources/com/walmartlabs/test_utils.clj
dev-resources/unknown-argument-type-schema.edn
src/com/walmartlabs/lacinia/schema.clj
test/com/walmartlabs/introspection_test.clj
test/com/walmartlabs/lacinia/arguments_test.clj
test/com/walmartlabs/lacinia/custom_scalars_test.clj
test/com/walmartlabs/lacinia/schema_test.clj
test/com/walmartlabs/lacinia/subscription_tests.clj
test/com/walmartlabs/lacinia/unions_test.clj
test/com/walmartlabs/lacinia/validator_test.clj
test/com/walmartlabs/lacinia_test.clj

This is something that is hard to catch via spec, and we can't be sure the application is using spec (they should!).
This adds checks that :resolve is present AND a function.
Fixes #90  ... but this builds on PR #90

Ensure that every query and mutation has a resolver function

---

docs/custom-scalars.rst
docs/fields.rst
docs/index.rst
docs/overview.rst
docs/queries.rst
docs/resolve/async.rst
docs/resolve/examples.rst
docs/resolve/exceptions.rst
docs/resolve/overview.rst
docs/resolve/resolve-as.rst
docs/resolve/selections.rst
docs/resolve/timing.rst
docs/subscriptions/streamer.rst
docs/unions.rst
src/com/walmartlabs/lacinia.clj
src/com/walmartlabs/lacinia/executor.clj
test/com/walmartlabs/lacinia/async_test.clj
test/com/walmartlabs/lacinia/enums_test.clj
test/com/walmartlabs/lacinia_test.clj

I've found the term 'response' (used in GraphQL specification) to be somewhat inaccurate, as we take that response as the body of a Ring/Pedestal response.  This PR simply updates the documentation to make this split more visible and consistent.

Use the term 'result map' instead of 'response'

---

src/com/walmartlabs/lacinia.clj
src/com/walmartlabs/lacinia/validation/fragment_names.clj
src/com/walmartlabs/lacinia/validation/no_unused_fragments.clj
src/com/walmartlabs/lacinia/validation/scalar_leafs.clj
src/com/walmartlabs/lacinia/validator.clj
test/com/walmartlabs/lacinia/validator_test.clj

Validation is not, at least currently, extensible, or intended for application code to invoke. This PR changes those namespaces to be invisible in the documentation.
The signatures of the validation functions are a bit out of date; the parsed and prepared query has everything needed, including the full schema if that is required.  The functions now simply receive the prepared schema.

Simplify validation and hide the namespaces

---

src/com/walmartlabs/lacinia/parser.clj
test/com/walmartlabs/lacinia/custom_scalars_test.clj
test/com/walmartlabs/lacinia/validator_test.clj
test/com/walmartlabs/lacinia_test.clj

Fixes issue #30 
Field arguments, fields of input objects and variables of type list will now allow input of a single value and will coerce it to a list of size one.

[20170717]  Allow single values on list type input

---

docs/resolve/async.rst
src/com/walmartlabs/lacinia/resolve.clj
test/com/walmartlabs/lacinia/resolver_result_test.clj

My concern is that when a mix of normal and async resolvers are operating inside core.async, a `go` block that resolves a promise could trigger a cascade of work that may include blocking I/O and lead to thread pool starvation.

Allow ResolverResultPromise callbacks to execute in a thread pool

---

dev-resources/doc-inheritance-schema.edn
docs/interfaces.rst
docs/objects.rst
src/com/walmartlabs/lacinia/schema.clj
test/com/walmartlabs/lacinia/async_test.clj
test/com/walmartlabs/lacinia/documentation_test.clj

This will help considerably with removing duplicated documentation when an interface and an object's field/argument documentation is the same.

Allow Field and argument :description to inherit from implemented interface

---

src/com/walmartlabs/lacinia/schema.clj
test/com/walmartlabs/lacinia/interfaces_test.clj

This PR fixes issue #17 
>The object field must include an argument of the same name for every argument defined in the interface field.
The object field may include additional arguments not defined in the interface field, but any additional argument must not be required.

Check that arguments on the field are compatible with arguments on the interface field

---

CHANGES.md
project.clj
src/com/walmartlabs/lacinia/schema.clj

Let's leave this as "defining functions as spec values is hard".  I believe what's going on is that clojure.spec is trying to create a function that returns a field resolver according to the fspec and that needs a library that isn't available at runtime. As with field resolvers and streamers, reducing the spec to just `fn?` fixes the problem.
When we're more comfortable w/ spec I'd like to revisit this; I believe it could be addressed by explicitly providing a generator as part of the spec.

Prevent a runtime error when using the :default-field-resolver option

---

CHANGES.md
dev-resources/com/walmartlabs/test_utils.clj
project.clj
src/com/walmartlabs/lacinia.clj
src/com/walmartlabs/lacinia/parser.clj
test/com/walmartlabs/lacinia/query_ops_test.clj

A trip up related to the code the ugly support for 'query' etc. as a operation/field/type name.

Fix bug (related to #114) that caused named operations to not work

---

src/com/walmartlabs/lacinia/internal_utils.clj

Clojure's `ExceptionInfo` constructor expects the data map passed to it to be non-null.  I encountered a situation where all the arguments to `merge` where `nil` which returns `nil`.  The actual Lacinia exception message is lost and you see  "Additional data must be non-nil."

Prevent an exception calling ex-info that can (rarely) occur because of nil ex-data

---

src/com/walmartlabs/lacinia/parser.clj

This PR resolves #143.
It changes the `com.walmartlabs.lacinia.parser/collect-default-values` method to filter out `:default-value` with the `some?` function instead of using the `identity` function.

Allow false to be used as a :default-value

---

dev-resources/nested-non-nullable-fields-schema.edn
src/com/walmartlabs/lacinia/parser.clj
test/com/walmartlabs/input_objects_test.clj
test/com/walmartlabs/lacinia/custom_scalars_test.clj
test/com/walmartlabs/lacinia/variables_test.clj
test/com/walmartlabs/lacinia_test.clj

Capture exception context at parse time for use with dynamic arguments
(from query variables)
Fixes #133

Fix null check for dynamic arguments

---

CHANGES.md
src/com/walmartlabs/lacinia/schema.clj
test/com/walmartlabs/lacinia/schema_test.clj

I've found that the incredibly verbose output when pr or pprint a compiled schema tends to overwhelm whatever debugging I'm doing.

Change the pr and pprint behavior for a compiled schema

---

CHANGES.md
src/com/walmartlabs/lacinia/schema.clj
test/com/walmartlabs/lacinia/enums_test.clj

- Failure to return a defined enum value (or nil) is now an exception, not a field error
- BUT it is legal again to return a string or symbol, which will be internally converted to a keyword

Be both more and less forgiving about enums

---

src/com/walmartlabs/lacinia/schema.clj
test/com/walmartlabs/lacinia/schema_test.clj

This change stops lacinia from turnning on spec assert checking globally
and manully checks the compile-args spec when compile is called.

manually check compile args against spec

---

CHANGES.md
dev-resources/root-object-schema.edn
dev-resources/root-object-with-conflicts-schema.edn
dev-resources/union-query-root-schema.edn
docs/_examples/parsed_sample_schema.edn
docs/index.rst
docs/mutations.rst
docs/queries.rst
docs/roots.rst
docs/schema/parsing.rst
docs/subscriptions/overview.rst
project.clj
src/com/walmartlabs/lacinia/constants.clj
src/com/walmartlabs/lacinia/internal_utils.clj
src/com/walmartlabs/lacinia/introspection.clj
src/com/walmartlabs/lacinia/parser.clj
src/com/walmartlabs/lacinia/parser/schema.clj
src/com/walmartlabs/lacinia/schema.clj
test/com/walmartlabs/lacinia/arguments_test.clj
test/com/walmartlabs/lacinia/parser/schema_test.clj
test/com/walmartlabs/lacinia/roots_test.clj
test/com/walmartlabs/lacinia/validator_test.clj

Other GraphQL implementations always define operations in terms of root objects; we're coming into this from an odd angle.
In any case, this also supports a root object actually being a union, in which case we merge together all the fields of all the members.
This simplifies the SDL parsing logic, as it can shift a lot of work to schema/compile, which includes new checks that the SDL code did not make (the check for conflicting names).
The merging of fields purposely leaves the `:qualified-field-name` unchanged, so you might end up with `:__Queries/foo` mixed in with `:QueryRoot/bar` & etc. I think this means that any errors reported (or exceptions thrown) involving such operations will be easier to interpret.  Check out the new and changed tests for examples.

Make it possible to define operations as fields of explicit root objects

---

docs/tutorial/init-schema.rst

When following the tutorial, the start function does not exist yet, nor is it necessary to run the query.

Tutorial: call to non-existing start function removed

---

CHANGES.md
dev-resources/enums.sdl
dev-resources/interfaces.sdl
dev-resources/unions.sdl
docs/_examples/parsed_sample_schema.edn
docs/schema/parsing.rst
project.clj
src/com/walmartlabs/lacinia/parser/schema.clj
test/com/walmartlabs/lacinia/parser/schema_test.clj

This includes an incompatible change to how we "path" a keyword to a location in the schema. It also adds support for documenting interfaces, enums, enum values,  and unions.

Changes and improvements to how SDL schema documentation is attached

---

CHANGES.md
dev-resources/basic-docs.md
dev-resources/preamble-docs.md
dev-resources/user.clj
src/com/walmartlabs/lacinia/internal_utils.clj
src/com/walmartlabs/lacinia/parser/docs.clj
src/com/walmartlabs/lacinia/parser/schema.clj
src/com/walmartlabs/lacinia/util.clj
test/com/walmartlabs/lacinia/parser/docs_test.clj
test/com/walmartlabs/lacinia/util_test.clj

Feedback on the naming of the various functions ... I'm vacillating between `attach-documentation` and `attach-descriptions`.

Add support for reading external Markdown file for schema documentation, then attaching it

---

dev-resources/input-object-schema.edn
src/com/walmartlabs/lacinia/parser.clj
test/com/walmartlabs/input_objects_test.clj

When the input object is provided as a variable but contains
invalid keys (not matching the input object definition)
then a confusing exception was thrown, rather than an exception
identifying the situation, object type, and field name.
Fixes #193.

Supplying invalid keys to an input object results in a confusing and unhelpful error

---

src/com/walmartlabs/lacinia/schema.clj
test/com/walmartlabs/lacinia/expound_tests.clj

Using `ifn?` instead of `fn?` allows passing vars of functions as resolver functions. 
```
(com.walmartlabs.lacinia.util/attach-resolvers
schema
{:query/game-by-id #'resolvers/game-by-id})
```
This can be handy during namespace reload when `attach-resolvers` call and the resolvers are declared in different namespaces.

Allow vars to be passed as resolver

---

CHANGES.md
dev-resources/documented-schema.sdl
dev-resources/duplicate-type.sdl
docs/schema/parsing.rst
resources/com/walmartlabs/lacinia/schema.g4
src/com/walmartlabs/lacinia/parser/common.clj
src/com/walmartlabs/lacinia/parser/query.clj
src/com/walmartlabs/lacinia/parser/schema.clj
src/com/walmartlabs/lacinia/schema.clj
test/com/walmartlabs/lacinia/parser/schema_test.clj

This is a follow-on to #216 that actually adds the support for descriptions before each schema element.

Implement descriptions inside Schema Definition Language documents as per June 2018 spec

---

src/com/walmartlabs/lacinia/parser.clj
src/com/walmartlabs/lacinia/util.clj
test/com/walmartlabs/lacinia/expound_tests.clj
test/com/walmartlabs/lacinia/roots_test.clj
test/com/walmartlabs/lacinia/util_test.clj

If `:resolve` value is an fn, `attach-callbacks` should skip it instead of trying to treat is as "factory" (which results in an exception). This behavior is useful when merging multiple schemas with already attached resolvers.
Ping @bcarrell, @hlship

When using attach-resolvers, if a field already has a function attached, it incorrectly treats it as a factory function reference

---

dev-resources/bad_schema.sdl
dev-resources/blockquote.sdl
dev-resources/documented-schema.sdl
dev-resources/duplicate-type.sdl
dev-resources/enums.sdl
dev-resources/interfaces.sdl
dev-resources/mult-inheritance.sdl
dev-resources/sample_schema.sdl
dev-resources/unions.sdl
docs/_examples/sample_schema.txt
resources/com/walmartlabs/lacinia/schema.g4
test/com/walmartlabs/lacinia/parser/schema_test.clj

The GraphQL spec does not seem to require this and the JS reference implementation of GraphQL fails to parse this syntax.

Fix SDL parsing to not improperly require wrapping curly braces

---

CHANGES.md
dev-resources/sample_schema.sdl
docs/_examples/directive-defs.edn
docs/deprecation.rst
docs/directives.rst
docs/schema/parsing.rst
project.clj
resources/com/walmartlabs/lacinia/schema.g4
src/com/walmartlabs/lacinia/compiled_schema.clj
src/com/walmartlabs/lacinia/parser.clj
src/com/walmartlabs/lacinia/parser/schema.clj
src/com/walmartlabs/lacinia/schema.clj
test/com/walmartlabs/lacinia/directives_test.clj
test/com/walmartlabs/lacinia/parser/schema_test.clj

What's here:
- parsing of directive definitions and directives in Schema Definition Language documents
- directive definitions may have documentation
- directives in schema elements are validated w.r.t. location
- @deprecated directive for field definitions and schema values
What's not here:
- type checking and coercion of directive arguments
- in fact, any validation of directive arguments
- an API to expose directives (type system or executable) to field resolvers 
- Introspection about directive definitions or element directives

Add limited support for directives

---

CHANGES.md
LICENCE.ordered.txt
README.md
project.clj
src/com/walmartlabs/lacinia/executor.clj
src/com/walmartlabs/lacinia/parser.clj
vendor-src/com/walmartlabs/lacinia/vendor/ordered/common.clj
vendor-src/com/walmartlabs/lacinia/vendor/ordered/map.clj
vendor-src/com/walmartlabs/lacinia/vendor/ordered/set.clj
vendor-src/com/walmartlabs/lacinia/vendor/useful/debug.clj
vendor-src/com/walmartlabs/lacinia/vendor/useful/experimental/delegate.clj
vendor-src/com/walmartlabs/lacinia/vendor/useful/ns.clj

This also applies a trivial patch to the ordered set implementation,
to provide JDK 11 compatibility.
To keep any future maintenance of this code easy, I did nothing to the vendored code beyond changing the namespace.
Fixes #237

Convert the flatland.ordered dependency to vendored code

---

docs/_examples/directive-defs.edn

`not-null` => `non-null`
I've signed the CLA

fix typo in directives example

---

dev-resources/mult-inheritance.sdl
resources/com/walmartlabs/lacinia/schema.g4
src/com/walmartlabs/lacinia/parser/schema.clj

A small change to consolidate the format required for implementing multiple interfaces when parsing a schema file to EDN.
The parser for a schema file to Lacinia's EDN appears to accept inheritance of multiple `space-separated` interfaces.
The [example from FB](https://facebook.github.io/graphql/draft/#sec-Interfaces) for implementing multiple interfaces is `ampersand-separated`.
It would be good if this was an option as in my scenario I am sharing one schema file between Lacinia  and a different JS library.
This isn't backwards compatible which may be an issue? I could change the regex to something like `'implements' (Name '&'?)* Name`.

Change schema parser to accept &-separated interfaces

---

resources/com/walmartlabs/lacinia/schema.g4
src/com/walmartlabs/lacinia/parser/common.clj
src/com/walmartlabs/lacinia/parser/schema.clj
test/com/walmartlabs/lacinia/parser/schema_test.clj

This pull request addresses #265 and #268 
The merging of `directives` for `extend type` is not perfect, and a `TODO` is added at that code line.
Thanks and kind regards.

GraphQL schema parsing support for extend type and empty type

---

CHANGES.md
docs/_examples/selections-tree.edn
docs/resolve/selections.rst
project.clj
src/com/walmartlabs/lacinia/executor.clj
test/com/walmartlabs/lacinia/optimize_resolve.clj
test/com/walmartlabs/lacinia/selections_tests.clj

The existing implementation is simpler, but fails when a selection includes the same field more than once, including via a fragment.  The new version maps each qualified field name to a vector of usage maps; the usage maps may include an :alias key.
Fixes #262

Change output from selections-tree to account for aliases

---

dev-resources/com/walmartlabs/test_schema.clj
src/com/walmartlabs/lacinia/schema.clj
test/com/walmartlabs/input_objects_test.clj
test/com/walmartlabs/introspection_test.clj
test/com/walmartlabs/lacinia/validator_test.clj
test/com/walmartlabs/lacinia_test.clj

Even some of our tests bent the rules here, and needed correction.
Fixes #254

Do not allow an InputObject as a field type (outside of another IO)

---

dev-resources/empty-input-objects.edn
src/com/walmartlabs/lacinia/parser.clj
test/com/walmartlabs/input_objects_test.clj

This pull request fixes the incorrect coercion of empty input objects to nils.
Previously, the query
```
query {
print_input (input: {})
}
```
would incorrectly pass `{:input nil}` args hashmap to the resolver of `print_input` while the correct args hashmap would be `{:input {}}`.

Don't transform empty objects to nils

---

docs/conf.py

http://facebook.github.io/graphql/... redirects to https://graphql.github.io/graphql-spec/ landing page, not to the particular topic we were trying to read about.

Fix extlink for GraphQL Spec

---

src/com/walmartlabs/lacinia/parser/schema.clj
src/com/walmartlabs/lacinia/schema.clj

This applies to parse/serialize functions as well.
Fixes #291

Allow a var, as well as a function, for resolvers and etc., to support REPL-oriented development

---

CHANGES.md
dev-resources/perf.clj
project.clj
src/com/walmartlabs/lacinia/executor.clj
test/com/walmartlabs/lacinia/selections_tests.clj

This makes a couple of enhancements to the preview API.
It fully supports using the preview API before query execution; the preview API then reflects the root operation(s).
A new function to get more useful data out of the selected fields.
Some benchmarks (see `perf`):
selections-tree:  134 µs
selections-tree + walk the tree (based on what eReceipts does): 479 µs
selections-seq: 78 µs
selections-seq2: 236 µs
The upshot is that we can get things done a little faster and without using undocumented/unsupported APIs.

Improvements to the executor namespace preview API

---

src/com/walmartlabs/lacinia/schema.clj
test/com/walmartlabs/lacinia_test.clj

When a collection is resolved, and a field resolver of one of its members raises an error, [the spec](https://graphql.github.io/graphql-spec/June2018/#sec-Errors) says that this error _should_ have a key `:path` with an index into that collection.
E.g. in this query:
```GraphQL
query {
hero {
friends {
name
}
}
}
```
If the second friend is nil, and name is required, an error with path `[:hero :friends 1 :name]` should be returned. This index is added to the `selector-context`, but should have been added
in the `execution-context` inside this `selector-context`. This caused this error path to inadvertently be `[:hero :friends :name]` (note the missing index).
Please note that this change can potentially add extra errors to the result because this index breaks the uniqueness of the error …

Fix an issue where error paths in collections were missing indices

---

CHANGES.md
src/com/walmartlabs/lacinia/parser.clj
test/com/walmartlabs/input_objects_test.clj
test/com/walmartlabs/interface_test.clj
test/com/walmartlabs/lacinia/arguments_test.clj
test/com/walmartlabs/lacinia/custom_scalars_test.clj
test/com/walmartlabs/lacinia/enums_test.clj
test/com/walmartlabs/lacinia/object_scalars_test.clj
test/com/walmartlabs/lacinia/scalar_tests.clj
test/com/walmartlabs/lacinia/validator_test.clj
test/com/walmartlabs/lacinia/variables_test.clj
test/com/walmartlabs/lacinia_test.clj

This was missed, allowing the nil to pass through the argument,
and cause NPEs inside resolver code.
As a drive by, I changed some of the exceptions to include fully qualified field and argument names (i.e., "Queries/get_movie.id" rather than just "id").

Detect when a non-null field is bound to a missing variable

---

src/com/walmartlabs/lacinia/schema.clj
test/com/walmartlabs/lacinia/enums_test.clj

After running a resolver, if we validate an enum field and find an invalid value, we throw an exception.
This seems sensible on the surface. However, if this happens while running an asynchronous resolver, the exception is throw in the secondary thread, after it `deliver!`s the promise. At that point, we cannot do anything with this error: the promise has already been delivered, so we cannot deliver a `(with-error ...)` value.
The result is that the secondary thread swallows the exception, and the main thread hangs forever, because we never finished handling the callback.
When we find an undefined enum value, we return a `selector-error` instead of throwing an exception, just like we do when we have a coercion failure, for example.

"Undefined enum value" errors return selector errors instead of throwing

---

src/com/walmartlabs/lacinia/executor.clj
src/com/walmartlabs/lacinia/validation/no_unused_fragments.clj
test/com/walmartlabs/lacinia/fragments_tests.clj

as described in a few places including here:
https://github.com/facebook/relay/issues/1937#issuecomment-324780567
I was getting the error message "Fragment Viewer_root is never used." when sending a query like the following to Lacinia:
```
query {
...Viewer_root
}
fragment Viewer_root on QueryRoot {
viewer {
id
username
}
}
```

support spreading fragments on root query

---

CHANGES.md
project.clj
resources/com/walmartlabs/lacinia/schema.g4
src/com/walmartlabs/lacinia/parser/schema.clj
test/com/walmartlabs/lacinia/parser/schema_test.clj

Previously, when parsing the input type from a schema, it was not possible to specify a default value for an input value; the grammar and parser have been extended to support this.
In addition, support for `extend input` has been added.

Update schema support: input value defaults and input extensions

---

CHANGES.md
dev-resources/field-resolver-errors.edn
docs/resolve/async.rst
docs/resolve/exceptions.rst
src/com/walmartlabs/lacinia/executor.clj
test/com/walmartlabs/lacinia/enums_test.clj
test/com/walmartlabs/lacinia/resolver_errors_test.clj

This PR ensures that uncaught exceptions thrown by resolver functions, or by code immediately after (such as field serializers, etc.) are caught and re-wrapped with more information (the qualified field name, the query location and path, the field arguments, and so forth).

Improve exceptions by identifying field and other data

---

CHANGES.md
docs/resolve/resolve-as.rst
src/com/walmartlabs/lacinia/executor.clj
test/com/walmartlabs/lacinia/resolve_test.clj

Prior to this PR, a field resolver that returns a map whose values included a ResolverResult (normally, a ResolverResultPromise) would operate incorrectly. An optimization in Lacinia for fields with a default field resolver would cause Lacinia  to ignore the fact that the nested value was an RR and just attempt to convert it to an output value; So the `str` of the ResolverResult if the field type was String, or an exception if the field type was numeric, etc.
This change tests the actual value returned by the field's default field resolver and ensures that it is unwrapped and otherwise processed the same.

Allow ResolverResult mixed with raw values

---

dev-resources/enum-default-value-with-transformer-schema.edn
src/com/walmartlabs/lacinia/introspection.clj
test/com/walmartlabs/introspection_test.clj

With custom scalars, if you have a default value in your schema.edn, you can use a 'parsed' value and for introspection, lacinia will transform it back to a 'serialized' value.
However, with enums, you can have a 'parsed' value in your schema, but there was no logic to convert it back to a serialized value prior to introspection. That left us between a rock and hard place, we could put a non-parsed default value in the schema, but then the enums parse function would not run prior to passing it as an argument (but introspection was correct), or we could put a parsed default value in the schema, but then the introspection result would be wrong.
Like scalars, this change invokes a possibly customly defined serialize function prior to returning a default value for introspection. So, if you …

Use possible enum serialisation in introspection of default value

---

CHANGES.md
dev-resources/no-entities-federation.sdl
dev-resources/simple-federation.sdl
docs/_examples/fed/external.gql
docs/_examples/fed/internal.gql
docs/_examples/fed/products.edn
docs/_examples/fed/query.gql
docs/_examples/fed/schema.gql
docs/conf.py
docs/federation/external.rst
docs/federation/implementation.rst
docs/federation/index.rst
docs/federation/internal.rst
docs/federation/reps.rst
docs/index.rst
project.clj
src/com/walmartlabs/lacinia/federation.clj
src/com/walmartlabs/lacinia/parser/schema.clj
test/com/walmartlabs/lacinia/federation_tests.clj

This extends Lacinia so that a Lacinia schema can be a service implementation within a Apollo GraphQL federated schema.
This first pass is limited to SDL-defined schemas, but that may change in the future.
I actually created a couple of services (using mocked data) and connected them using Apollo GraphQL, figuring out quite a few things along the way.

Add support for implementing Apollo GraphQL federation services

---

CHANGES.md
project.clj
resources/com/walmartlabs/lacinia/schema.g4
src/com/walmartlabs/lacinia/parser/schema.clj
test/com/walmartlabs/lacinia/parser/schema_test.clj

A bug in the SDL grammar meant that it was not possible to define a field, argument, or directive argument as having a default value of `true`, `false`, or `null`.

Fix bug with true/false/null literal values in SDL

---

src/com/walmartlabs/lacinia/schema.clj
test/com/walmartlabs/lacinia/directives_test.clj

Another oversight with respect to directives.

Allow directive arguments to be enums or input objects as well as scalara

---

docs/_examples/mutable-context.edn

```
[com.walmartlabs.lacina.resolve :as resolve]
```

mutable-context.edn typo: Requires lacina instead of lacinia

---

docs/samples.rst

New example is using the latest version of lacina-pedestal, and uses setting the host, so it works from docker.
Also the rest of the project has been updated to be more event sourcing, and not longer (also) relying on a sql database.

Replace the old example project with a refreshed one.

---

src/com/walmartlabs/lacinia/introspection.clj
test/com/walmartlabs/introspection_test.clj

The spec says that literals for input object values should not be JSON like (e.g. with string keys), but instead JS like (e.g. with name keys). This also applies for default values in introspection.
In these spec sections:
1. https://spec.graphql.org/June2018/#sec-Field-Arguments
DefaultValue here points to the shared DefaultValue, and that points to the normal Value.
2. https://spec.graphql.org/June2018/#ObjectValue
ObjectValue here does not permit quoted names. The example here is also without quotes.
The reference implementation also doesn't stringify keys:
https://codesandbox.io/s/elastic-wildflower-glwsh?file=/src/index.js
Unlike the reference implementation, this change does not add spaces between entries in the default value. I think thats fine, and more in line with how lacinia …

Don't stringify keys for defaults argument of input objects type

---

project.clj
src/com/walmartlabs/lacinia/resolve.clj
test/com/walmartlabs/lacinia/resolve_test.clj

In development mode, it is often useful to pass a Var (e.g, `#'my-resolver-fn`) so that changes to the Var during REPL oriented development can be accepted in realtime, without a re-start/re-compile of the schema.
This change fixes an edge case related to the new `:apply-field-directives` option and callback.

Allow a Var to be a resolver function

---

src/com/walmartlabs/lacinia/schema.clj
test/com/walmartlabs/interface_test.clj

Hi there,
Thanks for the very useful library!
I found this bug while trying to write some graphql of the form:
```
interface IA {
a: String
}
type A implements IA {
a: String!
}
```
I read through https://spec.graphql.org/June2018/#ObjectTypeDefinition and from my understanding of:
> 4. An object field type is a valid sub‐type if it is a Non‐Null variant of a valid sub‐type of the interface field type.
is that it is intended to be supported.
Looking through the existing code it looks like Lacinia also intended to support it, but had a bug.
Hopefully this is a reasonable fix to the issue.
I'm not 100% sure whether I've got the tests in the right place, or if I could do something better than `is some?`. Please let me know if there is a better alternative.
All the best,
Daniel

Support non-null object fields that implement nullable interface fields.

---

docs/tutorial/pedestal.rst

The [init-schema](https://github.com/walmartlabs/lacinia/blob/master/docs/tutorial/init-schema.rst#schema-edn-file) page uses the :description key to describe each field, instead of :documentation, so I believe that this is what was intended to be mentioned here.

Replace :documentation with :description in tutorial/pedestal docs page

---

docs/_examples/invoke-streamer.edn
docs/subscriptions/streamer.rst

This PR updates the documentation with an explanation and example of invoking the streamer when setting up a subscription. I thought this maybe helpful for others as I was confused from the docs how the source stream callback was used with the streamer.
If I can make any improvements to this please let me know.

Update documentation with invoke streamer example

---

resources/com/walmartlabs/lacinia/schema.g4
src/com/walmartlabs/lacinia/parser/schema.clj
src/com/walmartlabs/lacinia/resolve.clj
test/com/walmartlabs/lacinia/parser/schema_test.clj

This adds support for Union extensions, as described in https://spec.graphql.org/June2018/#sec-Union-Extensions.
currently [master](https://github.com/walmartlabs/lacinia/commit/8289c32e4af9fbf73793894268140619dd79172e) adds a typo which prevents tests from being run, this PR also fixes that in 8ec4e9fe67e74653dfbb2e3bbe26356510ed6a52.

Add support for extending unions

---

deps.edn
dev-resources/subscriptions-schema.edn
docs/subscriptions/streamer.rst
project.clj
src/com/walmartlabs/lacinia/executor.clj
src/com/walmartlabs/lacinia/resolve.clj
test/com/walmartlabs/lacinia/subscription_tests.clj

This was not previously documented, but has some valid use (such as `(resolve-as nil {...})` to indicate an error in the initial subscription query. Earlier changes in version 1.1 removed this support.
Fully fixing this requires changes to lacinia-pedestal as well: https://github.com/walmartlabs/lacinia-pedestal/tree/hls/wrapped-values-in-subscriptions

Restore support for ResolverResult passed to subscription stream callback

---

docs/_examples/tutorial/project-1.clj
docs/_examples/tutorial/project-2.clj
docs/_examples/tutorial/project-3.clj
docs/_examples/tutorial/project-4.clj
docs/_examples/tutorial/project-5.clj
docs/_examples/tutorial/server-1.clj
docs/_examples/tutorial/server-2.clj
docs/_examples/tutorial/user-3.clj
docs/tutorial/create-project.rst
docs/tutorial/database-1.rst
docs/tutorial/database-2.rst
docs/tutorial/game-data.rst
docs/tutorial/init-schema.rst
docs/tutorial/member-ratings.rst
docs/tutorial/pedestal.rst
docs/tutorial/testing-1.rst

While doing the tutorial, I used the latest dependency versions and everything worked well with a few clarifications I needed.
I've updated the tutorial documentation with some minor corrections. Adding `{:host "0.0.0.0"}` proved necessary to access GraphiQL at http://localhost:8888/

Tutorial refresh

---

src/com/walmartlabs/lacinia/schema.clj

Hi Walmart Team!
In Clashapp.co, we've faced an issue when the `::null` values remain in the response, for example:
```clojure
{:creator
{:backgroundGradient :OCEAN,
:bannedAt nil,
:bio "",
:createdAt "1970-01-01T00:00:01Z",
:isSubscriber false},
:createdAt "1970-01-01T00:00:00Z",
:updatedAt "2022-05-27T10:43:26.390451Z",
:isReported false,
:likeCount 1,
:text "",
:video :com.walmartlabs.lacinia.schema/null, ;; <--- !!
:replies nil,
:mentions [],
:isSubscriberOfVideoCreator false}
```
We expected the whole submap to collapse into `nil` because of the nested `::null` value. At least it was so before we updated from 1.0 to 1.1.
While investigating that, I noticed that only happens to the fields which are of the union type. In our case, the field was the `VideoCommentActivity` which is a …

Fix `can-reach-null-producer?` for union field

---

dev-resources/selection/argument-def-directive.sdl
src/com/walmartlabs/lacinia/schema.clj
src/com/walmartlabs/lacinia/selection.clj
test/com/walmartlabs/lacinia/parser/selection_test.clj

Add support for `Directives` to `ArgumentDef` so that field resolver functions can navigate from the `FieldSelection` instance returned by `com.walmartlabs.lacinia.executor/selection` to any directives placed on their arguments in the schema.

Make ArgumentDef protocol support Directives

---

CHANGES.md
dev-resources/subscriptions-schema.edn
src/com/walmartlabs/lacinia/schema.clj
test/com/walmartlabs/lacinia/subscription_tests.clj

Resolver functions can be preprocessed during compilation of the schema using the option `:apply-field-directives`.  Add a new option `:apply-subscription-field-directives` to allow streamer functions to be preprocessed in the same way.

Add a compilation option to apply field directives to streamer functions

---

src/com/walmartlabs/lacinia/parser.clj
test/com/walmartlabs/lacinia/arguments_test.clj

A bug occurs when dynamically inserting scalar variables into arguments of non-null list type.
```clojure
;; example
(let [schema (schema/compile {:queries
{:echo
{:type :String
:args {:input {:type '(non-null (list (non-null Int)))}}
:resolve (fn [_ args _]
(str "Echo: " (:input args)))}}})]
(execute schema "query($n1 : Int!, $n2 : Int!) { echo(input: [$n1, $n2]) }" {:n1 1 :n2 2} nil))
;; => {:data {:echo "Echo: [[1] [2]]"}} (unexpected, but current results)
;; => {:data {:echo "Echo: [1 2]"}} (expected)
```
This is caused by one less stripping of the `argument-definition` in the `process-dynamic-argument` method (when dispatch value is :array). In the case of `(non-null (list T))` argument type, there is one more level of `:kind :non-null` in argument-definition, so it has to be …

Providing a scalar value to an argument of type non-null list ends up with the scalar values wrapped as lists

---

src/com/walmartlabs/lacinia/parser.clj
test/com/walmartlabs/lacinia/arguments_test.clj
test/com/walmartlabs/lacinia_test.clj

Hi team!
Currently, when literal `null` is passed as an input to a `List` type argument, it gets coerced into an empty vector, which is incorrect. 
```clojure
(let [schema (schema/compile {:queries
{:echo
{:type :String
:args {:input {:type '(list (non-null Int))}}
:resolve (fn [_ args _]
(str "Echo: " (:input args)))}}})]
(execute schema "query { echo(input: null) }" nil nil))
=> {:data #ordered/map([:echo "Echo: []"])}
```
(The example format is borrowed from @duddlf23 's one :) )
However, according to https://spec.graphql.org/October2021/#sec-List.Input-Coercion, the input value should be coerced to list only if it is "not a list and not a null". So the correct result of the coercion should be `nil` in this case.
This is because the `mapv` function returns an empty vector when its …

Do not coerce nil into empty vector when an argument type is list and null is given

---

src/com/walmartlabs/lacinia/schema.clj

With zero corePoolSize and unlimited queue it doesn't increase the pool size and it keep using one single thread. If the intention was an unlimited queue with limited thread usage and keepAlive functionality with zero minimal thread then this change looks right for that.

Fix behaviour for default executor

---

src/com/walmartlabs/lacinia/schema.clj
test/com/walmartlabs/lacinia/directives_test.clj

Hi Walmart Labs,
While the @deprecated annotation is suported for enum values and type fields, it was not supported for input field definitions. GraphQL @deprecated directives are also valid on Input types in the most recent [Working Draft of the GraphQL Spec](http://spec.graphql.org/draft/#sec--deprecated).

Add support for @deprecated directives on :argument-definition, :input-field-definition

---

src/com/walmartlabs/lacinia/executor.clj
src/com/walmartlabs/lacinia/internal_utils.clj
test/com/walmartlabs/lacinia/merge_selections_test.clj

We noticed some exceptions being thrown after upgrading from 0.38.0 to 1.0
It seemed that when there is a list field both on an object and in a fragment, lacinia was attempting to do a map merge on the lists.
I've added a test which simulates the problem we had, and modified internal-utils/deep-merge so that it works on maps, sequentials and any other values.

Fix error when merging lists in fragments

---

src/com/walmartlabs/lacinia/executor.clj
test/com/walmartlabs/lacinia/executor_test.clj

(Rebase of #449)
I added an executor-test that wasn't there originally. Please see if this is the right way to go.

Fix runtime error when aggregating results with error-containing left-value

---

resources/com/walmartlabs/lacinia/schema.g4
test/com/walmartlabs/lacinia/parser/schema_test.clj

This change adds support for leading pipe values in union definitions. This was added to GraphQL in 2017.
This should address issue #465.

Support leading Pipes in Union Synatx

---

src/com/walmartlabs/lacinia/executor.clj
src/com/walmartlabs/lacinia/internal_utils.clj
test/com/walmartlabs/lacinia/executor_test.clj
test/com/walmartlabs/lacinia/internal_utils_tests.clj

Depending on the position of the fragment, you'll get inconsistent values.
I fixed a similar issue in #453, but in that case the fragment was nested, whereas this case is not.
This fails:
```graphql
query MyQuery {
node(id: "1000") {
... on Post {
id
...PostFragment
}
}
}
fragment PostFragment on Post {
author {
alwaysFail
}
...PostFragment2   # <--
}
fragment PostFragment2 on Post {
author {
name
}
}
```
While this is not:
```graphql
query MyQuery {
node(id: "1000") {
... on Post {
id
...PostFragment
}
}
}
fragment PostFragment on Post {
...PostFragment2   # <--
author {
alwaysFail
}
}
fragment PostFragment2 on Post {
author {
name
}
}
```
The reason seems to be that deep-merge is not commutative.
Given one of arguments is`nil` or `::null`, exception is thrown.

Fixes a runtime error that occurs when deep-merging fragments
