README.md
EDN fails to read due to duplicate entry
=> Removed duplicate map entry in README

docs/enums.rst, src/com/walmartlabs/lacinia/schema.clj, test/com/walmartlabs/lacinia/enums_test.clj
Fixes #1 
@annapawlicka @bcarrell
=> Allow enums to be strings, keywords, or symbols

src/com/walmartlabs/lacinia/internal_utils.clj
It seems the :else clause will just return nil if (nil? x) is true anyway. 
The 2 other commits are just performance enhancements (without making the code uglier (imho)).
Thanks for the lib, it's great stuff.
=> A few spot optimizations

dev-resources/perf.clj, src/com/walmartlabs/lacinia/executor.clj, src/com/walmartlabs/lacinia/introspection.clj, src/com/walmartlabs/lacinia/parser.clj, src/com/walmartlabs/lacinia/schema.clj, src/com/walmartlabs/lacinia/validation/fragment_names.clj, src/com/walmartlabs/lacinia/validation/scalar_leafs.clj, test/com/walmartlabs/lacinia/schema_test.clj, test/com/walmartlabs/lacinia/unions_test.clj, test/com/walmartlabs/lacinia_test.clj, test/com/walmartlabs/test_utils.clj
Removing a few unused bindings / namespaces Joker found.
=> Remove unused bindings / namespaces

dev-resources/typename-schema.edn, src/com/walmartlabs/lacinia/parser.clj, test/com/walmartlabs/lacinia/typename_test.clj, test/com/walmartlabs/test_utils.clj
=> Add support for __typename metadata

dev-resources/com/walmartlabs/test_schema.clj, src/com/walmartlabs/lacinia/parser.clj, test/com/walmartlabs/introspection_test.clj, test/com/walmartlabs/lacinia_test.clj
- create tests that cover the issue
- update parser process-result to recursively find the category of input objects
fixes #60
=> fix nested input arguments

CHANGES.md, dev-resources/com/walmartlabs/test_utils.clj, dev-resources/decorator-schema.edn, docs/_examples/decorator.edn, docs/resolve/decorator.rst, docs/resolve/index.rst, src/com/walmartlabs/lacinia/schema.clj, test/com/walmartlabs/lacinia/decorator_test.clj
Fixes #58 
More work to document than to implement.
=> Add support for decoration of resolver functions

CHANGES.md, dev-resources/variables-schema.edn, docs/custom-scalars.rst, src/com/walmartlabs/lacinia/schema.clj, test/com/walmartlabs/lacinia/custom_scalars_test.clj, test/com/walmartlabs/lacinia/variables_test.clj, test/com/walmartlabs/lacinia_test.clj
This one addresses a direct concern, #69 , and otherwise beefs up how we parse and coerce inputs into arguments, and selected fields into outputs.
=> Fix issues with parsing of scalars when variables are involved

dev-resources/com/walmartlabs/test_schema.clj, src/com/walmartlabs/lacinia/schema.clj, src/com/walmartlabs/lacinia/util.clj
=> Remove unused namespaces / bindings / vars

docs/_exts/remote.py, docs/_exts/remotecode.py, docs/_static/css/custom.css, docs/conf.py, docs/custom-scalars.rst, docs/directives.rst, docs/enums.rst, docs/fields.rst, docs/index.rst, docs/input-objects.rst, docs/interfaces.rst, docs/introspection.rst, docs/objects.rst, docs/queries.rst, docs/resolve/async.rst, docs/resolve/index.rst, docs/resolve/resolve-as.rst, docs/resolve/timing.rst, docs/subscriptions/index.rst, docs/subscriptions/overview.rst, docs/tutorial/create-project.rst, docs/tutorial/designer-data.rst, docs/tutorial/domain.rst, docs/tutorial/game-data.rst, docs/tutorial/index.rst, docs/tutorial/init-schema.rst, docs/tutorial/prereqs.rst, docs/tutorial/wrap-up.rst, docs/unions.rst
This adds and updates a pretty significant amount of documentation including the start of a tutorial.
=> Tutorial Phase 1

README.md, src/com/walmartlabs/lacinia.clj
=> Improve the documentation of variables for execute

src/com/walmartlabs/lacinia/schema.clj, test/com/walmartlabs/lacinia/schema_test.clj
Same PR as #130 but without the accidental version change.
=> Change list type check to sequential? to allow syntax quoted list types

src/com/walmartlabs/lacinia/parser.clj, src/com/walmartlabs/lacinia/schema.clj, test/com/walmartlabs/lacinia/parser/query_test.clj
=> Detect uncompiled schema at parse

src/com/walmartlabs/lacinia/introspection.clj, test/com/walmartlabs/introspection_test.clj
=> Properly return directive information in the introspection data

CHANGES.md, dev-resources/bad-resolver-enum.edn, docs/enums.rst, src/com/walmartlabs/lacinia/schema.clj, test/com/walmartlabs/lacinia/enums_test.clj
=> Ensure that field resolvers for enum types return valid values

docs/_examples/enum-definition-description.edn, docs/enums.rst, src/com/walmartlabs/lacinia/introspection.clj, src/com/walmartlabs/lacinia/schema.clj, test/com/walmartlabs/introspection_test.clj, test/com/walmartlabs/lacinia/schema_test.clj
=> Add support for enum descriptions

docs/_examples/object-tag.edn, docs/resolve/async.rst, docs/resolve/attach.rst, docs/resolve/overview.rst, docs/resolve/resolve-as.rst, docs/resolve/type-tags.rst, src/com/walmartlabs/lacinia/schema.clj, test/com/walmartlabs/lacinia/unions_test.clj
=> Allow object types to be identified via a Java class name

docs/enums.rst, src/com/walmartlabs/lacinia/schema.clj, test/com/walmartlabs/lacinia/enums_test.clj
=> Check for enum field resolver returning a non-keyword

src/com/walmartlabs/lacinia/resolve.clj
This removes the need for callers to check if a function before
invoking.
=> Change as-resolver-fn to work if passed a function

src/com/walmartlabs/lacinia/parser.clj, src/com/walmartlabs/lacinia/schema.clj
=> Use the CompiledSchema type, rather than meta-data

src/com/walmartlabs/lacinia/schema.clj, test/com/walmartlabs/lacinia/enums_test.clj
=> Clean up require, fix a test

CHANGES.md, src/com/walmartlabs/lacinia/util.clj, test/com/walmartlabs/lacinia/util_test.clj
This parallels the inject-descriptions utility in another PR
=> Add new inject-resolvers utility

CHANGES.md, dev-resources/user.clj, project.clj, src/com/walmartlabs/lacinia/expound.clj, src/com/walmartlabs/lacinia/schema.clj, test/com/walmartlabs/lacinia/expound_tests.clj, test/com/walmartlabs/lacinia/schema_test.clj
In addition, always enable Expound and update some tests for Expound's output (vs. the default output).
I also found a typo in an existing message.
=> Tweak definitions to get better expound output

CHANGES.md, dev-resources/input-object-default-value-schema.edn, dev-resources/list-default-value-schema.edn, dev-resources/non-string-default-value-schema.edn, project.clj, resources/com/walmartlabs/lacinia/introspection.edn, src/com/walmartlabs/lacinia/introspection.clj, test/com/walmartlabs/introspection_test.clj
=> Introspection: Properly output default values for field arguments as per the spec

src/com/walmartlabs/lacinia/schema.clj, test/com/walmartlabs/lacinia/unions_test.clj
=> Don't fail the member type test if the resolved value is nil

src/com/walmartlabs/lacinia/internal_utils.clj
=> Restore broken compatibility with Clojure 1.8

src/com/walmartlabs/lacinia/internal_utils.clj, src/com/walmartlabs/lacinia/util.clj, test/com/walmartlabs/lacinia/util_test.clj
=> Handle all variations of how enum values are defined when injecting descriptions

resources/com/walmartlabs/lacinia/Graphql.g4, src/com/walmartlabs/lacinia/parser/query.clj
This is just a little easier to understand and extend than the previous approach.
=> Improved way of handling names that conflict with reserved words

CHANGES.md, project.clj, src/com/walmartlabs/lacinia/internal_utils.clj, src/com/walmartlabs/lacinia/util.clj, test/com/walmartlabs/lacinia/internal_utils_tests.clj
=> Ensure that injected description and resolver paths are valid

CHANGES.md, dev-resources/lists-schema.edn, src/com/walmartlabs/lacinia/executor.clj, src/com/walmartlabs/lacinia/schema.clj, test/com/walmartlabs/introspection_test.clj, test/com/walmartlabs/lacinia/custom_scalars_test.clj, test/com/walmartlabs/lacinia/lists_tests.clj, test/com/walmartlabs/lacinia/resolver_errors_test.clj, test/com/walmartlabs/lacinia/wrapped_values_in_lists_tests.clj
=> A field resolver that resolves a nil should stay nil, not become an empty vector

docs/_examples/hero-query-response.edn
Added some "{" and ",". That's all.
=> I think there is an error on this response example.

dev-resources/com/walmartlabs/test_utils.clj, src/com/walmartlabs/lacinia/executor.clj, src/com/walmartlabs/lacinia/internal_utils.clj, src/com/walmartlabs/lacinia/parser.clj, src/com/walmartlabs/lacinia/schema.clj, src/com/walmartlabs/lacinia/validation/scalar_leafs.clj, src/com/walmartlabs/lacinia/validator.clj, test/com/walmartlabs/input_objects_test.clj, test/com/walmartlabs/interface_test.clj, test/com/walmartlabs/lacinia/arguments_test.clj, test/com/walmartlabs/lacinia/custom_scalars_test.clj, test/com/walmartlabs/lacinia/directives_test.clj, test/com/walmartlabs/lacinia/enums_test.clj, test/com/walmartlabs/lacinia/expound_tests.clj, test/com/walmartlabs/lacinia/field_tests.clj, test/com/walmartlabs/lacinia/interfaces_test.clj, test/com/walmartlabs/lacinia/merge_selections_test.clj, test/com/walmartlabs/lacinia/parser/schema_test.clj, test/com/walmartlabs/lacinia/schema_test.clj, test/com/walmartlabs/lacinia/unions_test.clj, test/com/walmartlabs/lacinia/validator_test.clj, test/com/walmartlabs/lacinia_test.clj
Less text by using the Object/field.arg syntax
*Defer Merge until 0.33.0 is active*
=> Make exceptions more consistent and concise

src/com/walmartlabs/lacinia/schema.clj, test/com/walmartlabs/lacinia/scalar_tests.clj, test/com/walmartlabs/lacinia_test.clj
=> Enforce that ID scalar values are an integer or a string

dev-resources/field-resolver-errors.edn, src/com/walmartlabs/lacinia/executor.clj, test/com/walmartlabs/lacinia/resolver_errors_test.clj
=> Properly merge extension data when adding in :path, :location, etc.

docs/resolve/type-tags.rst
`type-with-tag` -> `tag-with-type`
=> Minor typo

src/com/walmartlabs/lacinia/schema.clj
=> Allow a var, as well as a function, for streamers and default resolver to support REPL-oriented development

CHANGES.md, dev-resources/com/walmartlabs/test_utils.clj, project.clj, src/com/walmartlabs/lacinia/executor.clj, src/com/walmartlabs/lacinia/parser.clj, test/com/walmartlabs/lacinia/selections_tests.clj
=> Check for directives in the preview api

CHANGES.md, dev-resources/fragments-schema.edn, src/com/walmartlabs/lacinia/describe.clj, src/com/walmartlabs/lacinia/internal_utils.clj, src/com/walmartlabs/lacinia/parser.clj, src/com/walmartlabs/lacinia/validation/fragments.clj, src/com/walmartlabs/lacinia/validator.clj, test/com/walmartlabs/lacinia/fragments_tests.clj
=> Ensure fragments aren't cyclic

CHANGES.md, deps.edn, project.clj, src/com/walmartlabs/lacinia/resolve.clj, test/com/walmartlabs/lacinia/resolve_bindings_test.clj
=> Ensure that dynamic bindings are convered to callbacks even when a thread pool is being used

docs/tutorial/member-ratings.rst
The 66th line is missing from the newly added (emphasized) line.
=> Emphasize line 66

dev-resources/com/walmartlabs/test_utils.clj, dev-resources/dyn-args-schema.edn, src/com/walmartlabs/lacinia/parser.clj, test/com/walmartlabs/lacinia/input_types_test.clj
=> Fix NPE related to mix of literal and dynamic values in an input object

src/com/walmartlabs/lacinia/schema.clj
=> Compile input objects the same as normal objects

src/com/walmartlabs/lacinia/executor.clj
In certain cases, very large queries could result in a StackOverflowError, because com.walmartlabs.lacinia.executor/walk-selections was implemented recursively; this changes its implementation to work with a queue, and adds other performance enhancements.
This would only affect applications making use of the "preview" functions in the executor namespace.
=> Avoid stack overflow on very large queries

deps.edn
=> Update clj-anltr dependency (due to CVE-2020-21913)

CHANGES.md, dev-resources/subscription-selection.edn, src/com/walmartlabs/lacinia/executor.clj, test/com/walmartlabs/lacinia/subscription_tests.clj
=> Enable preview API for subscription streamers

test/com/walmartlabs/lacinia/directives_test.clj
I originally wrote this test to serve as a bug report, but it's already passing. 
Still, it adds an explicit test for an obscure feature so I thought it useful to share with the project even in its passing form.
=> Add test for using directives in external fragments

src/com/walmartlabs/lacinia/parser.clj, test/com/walmartlabs/input_objects_test.clj
=> Improve error message for invalid value for input object

src/com/walmartlabs/lacinia/schema.clj
=> Apply default resolver to all subscriptions missing :resolve

docs/_examples/tutorial/schema-6.clj, docs/_examples/tutorial/user-1.clj, docs/tutorial/init-schema.rst, docs/tutorial/member-ratings.rst
Fixes some typos and broken-code-examples in the tutorial.
=> Tutorial Errata
